### ISSUE TITLE
Where does the MACHINE_OPTS come from?

### ISSUE THREAD

**Issue by BraunreutherA** [dweomer/docker-swarm-consul#3]
Hi there, 

I'm setting up the script to deploy the swarm cluster on a on premise server. Actually the `setup-machines.sh` script hast the `${MACHINE_OPTS}` variable in it which doesn't get specified anywhere. Do I have to set it on my own before executing the script?

**Comment by dweomer** [comment]
`${MACHINE_OPTS}` is not required. I included it in the scripts as it allows you to specify global flags for `docker-machine`, such as `--debug`.

**Comment by BraunreutherA** [comment]
Okay thanks.
